### ISSUE TITLE
似乎不支持多多边形

### ISSUE THREAD

**Issue by Preyou** [hongfaqiu/shp-write-multi#1]
我们更希望导出单个shp，而不是一组shp，所以能否支持多多边形？

**Comment by hongfaqiu** [comment]
你好，我记得[原作者仓库](https://github.com/mapbox/shp-write)就是导出单个shp的，你可以看一下

**Comment by Preyou** [comment]
谢谢，已经用原仓库的包解决了。但是原仓库的包好像也不支持多多边形，只能先把多多变形扁平化后再导出。
